import React, { useState, useEffect } from 'react';
import { Plus, Search, Trash2, AlertTriangle, Zap } from 'lucide-react';
import { api } from '../api';
import type { InternalLink } from '../types';
import Modal from '../components/ui/Modal';

type OrphanPage = {
    id: number;
    title: string;
};

type InternalLinkSuggestion = {
    target_page_id: number;
    target_page_title: string;
    suggested_anchor_text: string;
    relevance_score: number;
};

type AxiosErrorLike = {
    response?: {
        status?: number;
        data?: {
            message?: string;
        };
    };
};

const getAxiosStatus = (error: unknown) => {
    if (typeof error !== 'object' || error === null) return undefined;
    const maybe = error as AxiosErrorLike;
    return maybe.response?.status;
};

const getAxiosMessage = (error: unknown, fallback: string) => {
    if (typeof error !== 'object' || error === null) return fallback;
    const maybe = error as AxiosErrorLike;
    return maybe.response?.data?.message || fallback;
};

const isPaginatedResponse = (value: unknown): value is { data: unknown[] } => {
    if (typeof value !== 'object' || value === null) return false;
    const maybe = value as { data?: unknown };
    return Array.isArray(maybe.data);
};

const isOrphanPage = (value: unknown): value is OrphanPage => {
    if (typeof value !== 'object' || value === null) return false;
    const maybe = value as Record<string, unknown>;
    return typeof maybe.id === 'number' && typeof maybe.title === 'string';
};

const InternalLinkManager = () => {
    const [links, setLinks] = useState<InternalLink[]>([]);
    const [orphanPages, setOrphanPages] = useState<OrphanPage[]>([]);
    const [loading, setLoading] = useState(true);
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [currentLink, setCurrentLink] = useState<Partial<InternalLink>>({});
    const [searchTerm, setSearchTerm] = useState('');
    const [isSuggestModalOpen, setIsSuggestModalOpen] = useState(false);
    const [suggestSourcePageId, setSuggestSourcePageId] = useState<number | ''>('');
    const [suggestions, setSuggestions] = useState<InternalLinkSuggestion[]>([]);
    const [suggestionSelection, setSuggestionSelection] = useState<Record<number, boolean>>({});
    const [suggestLoading, setSuggestLoading] = useState(false);
    const [applyLoading, setApplyLoading] = useState(false);
    const [suggestError, setSuggestError] = useState<string | null>(null);
    const [suggestResult, setSuggestResult] = useState<string | null>(null);

    const fetchData = async () => {
        setLoading(true);
        try {
            const [linksRes, orphansRes] = await Promise.all([
                api.get('/internal-links'),
                api.get('/internal-links/orphans')
            ]);
            const linksData: unknown = linksRes.data;
            const rawLinks: unknown[] = Array.isArray(linksData) ? linksData : isPaginatedResponse(linksData) ? linksData.data : [];
            const normalizedLinks = rawLinks.map((link) => {
                const record = typeof link === 'object' && link !== null ? (link as Record<string, unknown>) : {};
                const autoGenerated = typeof record.auto_generated === 'boolean' ? record.auto_generated : false;
                return {
                    ...(record as unknown as InternalLink),
                    auto_generated: autoGenerated,
                    is_manual: typeof record.is_manual === 'boolean' ? record.is_manual : !autoGenerated,
                } as InternalLink;
            });
            setLinks(normalizedLinks);
            const orphansData: unknown = orphansRes.data;
            const rawOrphans: unknown[] = Array.isArray(orphansData) ? orphansData : isPaginatedResponse(orphansData) ? orphansData.data : [];
            setOrphanPages(rawOrphans.filter(isOrphanPage));
        } catch (error) {
            console.error('Failed to fetch SEO data', error);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchData();
    }, []);

    const handleSave = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            await api.post('/internal-links', { ...currentLink, auto_generated: false });
            setIsModalOpen(false);
            fetchData();
        } catch (error) {
            console.error('Failed to save link', error);
        }
    };

    const handleDelete = async (id: number) => {
        if (confirm('Are you sure you want to remove this internal link?')) {
            try {
                await api.delete(`/internal-links/${id}`);
                fetchData();
            } catch (error) {
                console.error('Failed to delete link', error);
            }
        }
    };

    const handleAutoSuggest = async () => {
        setIsSuggestModalOpen(true);
        setSuggestSourcePageId('');
        setSuggestions([]);
        setSuggestionSelection({});
        setSuggestError(null);
        setSuggestResult(null);
    };

    const fetchSuggestions = async () => {
        if (!suggestSourcePageId) return;
        setSuggestLoading(true);
        setSuggestError(null);
        setSuggestResult(null);
        try {
            const res = await api.get('/internal-links/suggest', { params: { source_page_id: suggestSourcePageId } });
            const nextSuggestions: InternalLinkSuggestion[] = Array.isArray(res.data) ? res.data : [];
            setSuggestions(nextSuggestions);
            const nextSelection: Record<number, boolean> = {};
            for (const s of nextSuggestions) {
                nextSelection[s.target_page_id] = true;
            }
            setSuggestionSelection(nextSelection);
        } catch (error) {
            setSuggestError(getAxiosMessage(error, 'Failed to fetch suggestions'));
        } finally {
            setSuggestLoading(false);
        }
    };

    const applySuggestions = async () => {
        if (!suggestSourcePageId) return;
        const selected = suggestions.filter((s) => suggestionSelection[s.target_page_id]);
        if (selected.length === 0) return;

        setApplyLoading(true);
        setSuggestError(null);
        setSuggestResult(null);

        try {
            const results = await Promise.allSettled(
                selected.map((s) =>
                    api.post('/internal-links', {
                        source_page_id: suggestSourcePageId,
                        target_page_id: s.target_page_id,
                        anchor_text: s.suggested_anchor_text?.trim() || s.target_page_title,
                        auto_generated: true,
                    })
                )
            );

            const created = results.filter((r) => r.status === 'fulfilled').length;
            const conflicts = results.filter((r) => r.status === 'rejected' && getAxiosStatus(r.reason) === 409).length;
            const failed = results.length - created - conflicts;

            const parts: string[] = [];
            parts.push(`${created} links created`);
            if (conflicts) parts.push(`${conflicts} already existed`);
            if (failed) parts.push(`${failed} failed`);
            setSuggestResult(parts.join(', '));
            fetchData();
        } catch (error) {
            setSuggestError(getAxiosMessage(error, 'Failed to apply suggestions'));
        } finally {
            setApplyLoading(false);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-gray-800">Internal Linking</h1>
                    <p className="text-gray-500">Manage internal link structure and orphan pages</p>
                </div>
                <div className="flex gap-2">
                    <button 
                        onClick={handleAutoSuggest}
                        className="flex items-center gap-2 bg-purple-100 text-purple-700 px-4 py-2 rounded-lg hover:bg-purple-200 transition-colors"
                    >
                        <Zap size={20} />
                        <span>Auto Suggest</span>
                    </button>
                    <button 
                        onClick={() => { setCurrentLink({}); setIsModalOpen(true); }}
                        className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition-colors"
                    >
                        <Plus size={20} />
                        <span>Add Link</span>
                    </button>
                </div>
            </div>

            {orphanPages.length > 0 && (
                <div className="bg-orange-50 border border-orange-200 rounded-xl p-4 flex items-start gap-3">
                    <AlertTriangle className="text-orange-500 shrink-0 mt-1" size={20} />
                    <div>
                        <h3 className="font-semibold text-orange-800">Orphan Pages Detected</h3>
                        <p className="text-orange-700 text-sm mt-1">
                            {orphanPages.length} pages have no internal links pointing to them. Consider linking to these pages to improve SEO.
                        </p>
                        <div className="mt-2 flex flex-wrap gap-2">
                            {orphanPages.slice(0, 5).map(page => (
                                <span key={page.id} className="inline-flex items-center px-2 py-1 rounded bg-white text-xs font-medium text-orange-800 border border-orange-100">
                                    {page.title}
                                </span>
                            ))}
                            {orphanPages.length > 5 && (
                                <span className="text-xs text-orange-600 self-center">+{orphanPages.length - 5} more</span>
                            )}
                        </div>
                    </div>
                </div>
            )}

            <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
                <div className="p-4 border-b border-gray-100 bg-gray-50/50">
                    <div className="relative max-w-md">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={20} />
                        <input 
                            type="text"
                            placeholder="Search links..."
                            className="w-full pl-10 pr-4 py-2 border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                        />
                    </div>
                </div>

                <div className="overflow-x-auto">
                    <table className="w-full">
                        <thead className="bg-gray-50 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                            <tr>
                                <th className="px-6 py-4">Source Page</th>
                                <th className="px-6 py-4">Target Page</th>
                                <th className="px-6 py-4">Anchor Text</th>
                                <th className="px-6 py-4">Type</th>
                                <th className="px-6 py-4 text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100">
                            {loading ? (
                                <tr>
                                    <td colSpan={5} className="px-6 py-8 text-center text-gray-500">Loading links...</td>
                                </tr>
                            ) : links.length === 0 ? (
                                <tr>
                                    <td colSpan={5} className="px-6 py-8 text-center text-gray-500">No internal links found.</td>
                                </tr>
                            ) : (
                                links.map((link) => (
                                    <tr key={link.id} className="hover:bg-gray-50/50 transition-colors">
                                        <td className="px-6 py-4 text-sm text-gray-900">
                                            Page #{link.source_page_id}
                                        </td>
                                        <td className="px-6 py-4 text-sm text-gray-900">
                                            Page #{link.target_page_id}
                                        </td>
                                        <td className="px-6 py-4 text-sm text-gray-600">
                                            "{link.anchor_text}"
                                        </td>
                                        <td className="px-6 py-4">
                                            <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                                                link.is_manual ? 'bg-blue-100 text-blue-800' : 'bg-gray-100 text-gray-800'
                                            }`}>
                                                {link.is_manual ? 'Manual' : 'Auto'}
                                            </span>
                                        </td>
                                        <td className="px-6 py-4 text-right">
                                            <button 
                                                onClick={() => handleDelete(link.id)}
                                                className="p-2 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
                                            >
                                                <Trash2 size={18} />
                                            </button>
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            <Modal
                isOpen={isModalOpen}
                onClose={() => setIsModalOpen(false)}
                title="Add Internal Link"
            >
                <form onSubmit={handleSave} className="space-y-4">
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Source Page ID</label>
                        <input
                            type="number"
                            required
                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
                            value={currentLink.source_page_id || ''}
                            onChange={(e) => setCurrentLink({ ...currentLink, source_page_id: Number(e.target.value) })}
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Target Page ID</label>
                        <input
                            type="number"
                            required
                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
                            value={currentLink.target_page_id || ''}
                            onChange={(e) => setCurrentLink({ ...currentLink, target_page_id: Number(e.target.value) })}
                        />
                    </div>
                    <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">Anchor Text</label>
                        <input
                            type="text"
                            required
                            className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500"
                            value={currentLink.anchor_text || ''}
                            onChange={(e) => setCurrentLink({ ...currentLink, anchor_text: e.target.value })}
                        />
                    </div>
                    <div className="flex justify-end gap-3 pt-4">
                        <button
                            type="button"
                            onClick={() => setIsModalOpen(false)}
                            className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
                        >
                            Cancel
                        </button>
                        <button
                            type="submit"
                            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                        >
                            Create Link
                        </button>
                    </div>
                </form>
            </Modal>

            <Modal
                isOpen={isSuggestModalOpen}
                onClose={() => setIsSuggestModalOpen(false)}
                title="Auto Suggest Internal Links"
                size="xl"
                footer={
                    <div className="flex items-center justify-between gap-4">
                        <div className="text-sm">
                            {suggestError ? (
                                <span className="text-red-600">{suggestError}</span>
                            ) : suggestResult ? (
                                <span className="text-green-700">{suggestResult}</span>
                            ) : null}
                        </div>
                        <div className="flex gap-3">
                            <button
                                type="button"
                                onClick={() => setIsSuggestModalOpen(false)}
                                className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors"
                                disabled={suggestLoading || applyLoading}
                            >
                                Close
                            </button>
                            <button
                                type="button"
                                onClick={applySuggestions}
                                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 transition-colors disabled:opacity-50"
                                disabled={suggestLoading || applyLoading || !suggestSourcePageId || suggestions.length === 0}
                            >
                                {applyLoading ? 'Applying...' : 'Create Selected Links'}
                            </button>
                        </div>
                    </div>
                }
            >
                <div className="space-y-4">
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-3 items-end">
                        <div>
                            <label className="block text-sm font-medium text-gray-700 mb-1">Source Page ID</label>
                            <input
                                type="number"
                                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500/20 focus:border-purple-500"
                                value={suggestSourcePageId}
                                onChange={(e) => setSuggestSourcePageId(e.target.value ? Number(e.target.value) : '')}
                                min={1}
                            />
                        </div>
                        <div className="md:col-span-2 flex gap-3">
                            <button
                                type="button"
                                onClick={fetchSuggestions}
                                className="px-4 py-2 bg-purple-100 text-purple-700 rounded-lg hover:bg-purple-200 transition-colors disabled:opacity-50"
                                disabled={suggestLoading || applyLoading || !suggestSourcePageId}
                            >
                                {suggestLoading ? 'Loading...' : 'Get Suggestions'}
                            </button>
                            <button
                                type="button"
                                onClick={() => {
                                    const allSelected = suggestions.length > 0 && suggestions.every((s) => suggestionSelection[s.target_page_id]);
                                    const next: Record<number, boolean> = {};
                                    for (const s of suggestions) next[s.target_page_id] = !allSelected;
                                    setSuggestionSelection(next);
                                }}
                                className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg transition-colors disabled:opacity-50"
                                disabled={suggestLoading || applyLoading || suggestions.length === 0}
                            >
                                Toggle All
                            </button>
                        </div>
                    </div>

                    <div className="border border-gray-100 rounded-xl overflow-hidden">
                        <table className="w-full">
                            <thead className="bg-gray-50 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">
                                <tr>
                                    <th className="px-4 py-3 w-12"></th>
                                    <th className="px-4 py-3">Target Page</th>
                                    <th className="px-4 py-3">Anchor Text</th>
                                    <th className="px-4 py-3 text-right">Score</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-gray-100">
                                {suggestions.length === 0 ? (
                                    <tr>
                                        <td colSpan={4} className="px-4 py-6 text-center text-sm text-gray-500">
                                            {suggestSourcePageId ? 'No suggestions yet. Click “Get Suggestions”.' : 'Enter a source page ID to fetch suggestions.'}
                                        </td>
                                    </tr>
                                ) : (
                                    suggestions.map((s) => (
                                        <tr key={s.target_page_id} className="hover:bg-gray-50/50 transition-colors">
                                            <td className="px-4 py-3">
                                                <input
                                                    type="checkbox"
                                                    checked={!!suggestionSelection[s.target_page_id]}
                                                    onChange={(e) =>
                                                        setSuggestionSelection((prev) => ({
                                                            ...prev,
                                                            [s.target_page_id]: e.target.checked,
                                                        }))
                                                    }
                                                />
                                            </td>
                                            <td className="px-4 py-3 text-sm text-gray-900">{s.target_page_title}</td>
                                            <td className="px-4 py-3 text-sm text-gray-700">{s.suggested_anchor_text || '—'}</td>
                                            <td className="px-4 py-3 text-right text-sm text-gray-700">{s.relevance_score}</td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                        </table>
                    </div>
                </div>
            </Modal>
        </div>
    );
};

export default InternalLinkManager;
